# Generated by Django 2.2.12 on 2020-05-26 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('plate', models.CharField(max_length=10)),
                ('vin', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=255)),
                ('color', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OdomSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('mileage', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodo.Car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odomSnapshot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dueMileage', models.FloatField()),
                ('dueDate', models.DateTimeField()),
                ('estimatedDueDate', models.BooleanField(default=False)),
                ('mileageRepeatInterval', models.FloatField()),
                ('daysRepeatInterval', models.IntegerField()),
                ('monthsRepeatInterval', models.IntegerField()),
                ('yearsRepeatInterval', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodo.Car')),
                ('completionOdomSnapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodo.OdomSnapshot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('amount', models.FloatField()),
                ('odomSnapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodo.OdomSnapshot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refueling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
