# Generated by Django 3.1.7 on 2021-03-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodo', '0002_auto_20210302_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
