# Generated by Django 2.2.12 on 2020-05-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodo', '0002_auto_20200525_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='imageName',
            new_name='image',
        ),
    ]
