# Generated by Django 2.2.12 on 2020-05-26 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autodo', '0003_auto_20200525_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='odomsnapshot',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='odomSnapshot', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
