# Generated by Django 3.2 on 2021-04-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodo', '0005_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
