version: "3.7"

services:
  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=autodo
      - POSTGRES_PASSWORD=autodo
      - POSTGRES_DB=autodo_dev
  frontend:
    build: ./frontend
    working_dir: /app
    command: ./entrypoint.sh
    ports:
      - 8080:8080
    volumes:
      - ./frontend/:/app
      - /app/node_modules/
    depends_on:
      - api
  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: api:8000
      NGROK_PROTOCOL: http
  flutter:
    build: ./mobile
    working_dir: /mobile
    command: ./entrypoint.sh
    volumes:
      - ./mobile/:/mobile
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - /dev/bus/usb:/dev/bus/usb
    depends_on:
      - api
      - ngrok

volumes:
  postgres_data:
  static_volume:
  media_volume:
  backend:
  mobile:
