# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    always_declare_return_types: error
    await_only_futures: error
    directives_ordering: warning
    file_names: error
    prefer_final_fields: error
    prefer_relative_imports: warning
    prefer_single_quotes: error
    prefer_typing_uninitialized_variables: error
    todo: ignore
    unawaited_futures: warning
    unnecessary_parenthesis: error
    use_function_type_syntax_for_parameters: warning

linter:
  rules:
    - always_declare_return_types
    - avoid_void_async
    - await_only_futures
    - directives_ordering
    - file_names
    - omit_local_variable_types
    - prefer_const_constructors_in_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - sort_constructors_first
    - sort_unnamed_constructors_first
    # - type_annotate_public_apis
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - void_checks
