# Generated by Django 2.2.16 on 2020-09-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autodo", "0004_auto_20200913_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odomsnapshot",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snaps",
                to="autodo.Car",
            ),
        ),
    ]
