# Generated by Django 2.2.16 on 2020-10-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodo', '0005_auto_20200927_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odomsnapshot',
            options={'ordering': ['-mileage']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['dueDate', 'dueMileage']},
        ),
    ]
