import 'dart:ui';

import 'package:flutter/widgets.dart';
import 'package:intl/intl.dart';
import 'package:preferences/preferences.dart';
import 'package:provider/provider.dart';

import 'conversion.dart';

class Currency extends UnitConversion<String> {
  const Currency(String unit, Locale locale) : super(unit, locale);

  factory Currency.of(BuildContext context, {bool listen = true}) => Currency(
        Provider.of<BasePrefService>(
          context,
          listen: listen,
        ).getString('currency'),
        Localizations.localeOf(context),
      );

  @override
  String format(num value, {bool textField = false}) {
    if (value == null) {
      return '';
    }

    value = internalToUnit(value);

    if (textField) {
      // ToDo: might change depending on the currency
      return value.toStringAsFixed(2);
    }

    return NumberFormat.simpleCurrency(
      locale: locale.toLanguageTag(),
      name: unit,
    ).format(value);
  }

  @override
  String unitString(BuildContext context, {bool short = false}) {
    if (short) {
      return unit;
    }

    return currencies[unit] ?? unit;
  }

  @override
  num internalToUnit(num value) {
    return value;
  }

  @override
  num unitToInternal(num value) {
    return value;
  }

  static String getDefault(Locale locale) {
    return countryCodes[locale.countryCode] ?? 'USD';
  }

  static const currencies = <String, String>{
    'AED': 'Dirham',
    'AFN': 'Afghani',
    'ALL': 'Lek',
    'AMD': 'Dram',
    'ANG': 'Netherlands Antilles Guilder',
    'AOA': 'Angolan kwanza',
    'AQD': 'Antarctican dollar',
    'ARS': 'Peso',
    'AUD': 'Australian Dollars',
    'AZN': 'Manat',
    'BAM': 'Bosnia and Herzegovina convertible mark',
    'BBD': 'Barbadian Dollar',
    'BDT': 'Taka',
    'BGN': 'Lev',
    'BHD': 'Bahraini Dinar',
    'BIF': 'Burundi Franc',
    'BMD': 'Bermudian Dollar',
    'BND': 'Bruneian Dollar',
    'BOB': 'Boliviano',
    'BRL': 'Brazil',
    'BSD': 'Bahamian Dollar',
    'BWP': 'Pula',
    'BYR': 'Belarus Ruble',
    'BZD': 'Belizean Dollar',
    'CAD': 'Canadian Dollar',
    'CDF': 'Congolese Frank',
    'CHF': 'Swiss Franc',
    'CLP': 'Chilean Peso',
    'CNY': 'Yuan Renminbi',
    'COP': 'Peso',
    'CRC': 'Costa Rican Colon',
    'CUP': 'Cuban Peso',
    'CVE': 'Escudo',
    'CYP': 'Cypriot Pound',
    'CZK': 'Koruna',
    'DJF': 'Djiboutian Franc',
    'DKK': 'Danish Krone',
    'DOP': 'Dominican Peso',
    'DZD': 'Algerian Dinar',
    'ECS': 'Sucre',
    'EEK': 'Estonian Kroon',
    'EGP': 'Egyptian Pound',
    'ETB': 'Ethiopian Birr',
    'EUR': 'Euros',
    'FJD': 'Fijian Dollar',
    'FKP': 'Falkland Pound',
    'GBP': 'Sterling',
    'GEL': 'Lari',
    'GGP': 'Guernsey pound',
    'GHS': 'Ghana cedi',
    'GIP': 'Gibraltar Pound',
    'GMD': 'Dalasi',
    'GNF': 'Guinean Franc',
    'GTQ': 'Quetzal',
    'GYD': 'Guyanaese Dollar',
    'HKD': 'HKD',
    'HNL': 'Lempira',
    'HRK': 'Croatian Dinar',
    'HTG': 'Gourde',
    'HUF': 'Forint',
    'IDR': 'Indonesian Rupiah',
    'ILS': 'Shekel',
    'INR': 'Indian Rupee',
    'IQD': 'Iraqi Dinar',
    'IRR': 'Iranian Rial',
    'ISK': 'Icelandic Krona',
    'JMD': 'Jamaican Dollar',
    'JOD': 'Jordanian Dinar',
    'JPY': 'Japanese Yen',
    'KES': 'Kenyan Shilling',
    'KGS': 'Som',
    'KHR': 'Riel',
    'KMF': 'Comoran Franc',
    'KPW': 'Won',
    'KRW': 'Won',
    'KWD': 'Kuwaiti Dinar',
    'KYD': 'Caymanian Dollar',
    'KZT': 'Tenge',
    'LAK': 'Lao Kip',
    'LBP': 'Lebanese Pound',
    'LKR': 'Rupee',
    'LRD': 'Liberian Dollar',
    'LSL': 'Loti',
    'LTL': 'Lita',
    'LVL': 'Lat',
    'LYD': 'Libyan Dinar',
    'MAD': 'Dirham',
    'MDL': 'Leu',
    'MGA': 'Malagasy Franc',
    'MKD': 'Denar',
    'MMK': 'Kyat',
    'MNT': 'Tugrik',
    'MOP': 'Macanese Pataca',
    'MRO': 'Ouguiya',
    'MTL': 'Maltese Lira',
    'MUR': 'Mauritian Rupee',
    'MVR': 'Rufiyaa',
    'MWK': 'Malawian Kwacha',
    'MXN': 'Peso',
    'MYR': 'Ringgit',
    'MZN': 'Metical',
    'NAD': 'Dollar',
    'NGN': 'Naira',
    'NIO': 'Cordoba Oro',
    'NOK': 'Norwegian Krone',
    'NPR': 'Nepalese Rupee',
    'NZD': 'New Zealand Dollars',
    'OMR': 'Sul Rial',
    'PAB': 'Balboa',
    'PEN': 'Nuevo Sol',
    'PGK': 'Kina',
    'PHP': 'Peso',
    'PKR': 'Rupee',
    'PLN': 'Zloty',
    'PYG': 'Guarani',
    'QAR': 'Rial',
    'RON': 'Leu',
    'RSD': 'Serbian dinar',
    'RUB': 'Ruble',
    'RWF': 'Rwanda Franc',
    'SAR': 'Riyal',
    'SBD': 'Solomon Islands Dollar',
    'SCR': 'Rupee',
    'SDG': 'Dinar',
    'SEK': 'Krona',
    'SGD': 'Dollar',
    'SKK': 'Koruna',
    'SLL': 'Leone',
    'SOS': 'Shilling',
    'SRD': 'Surinamese Guilder',
    'STD': 'Dobra',
    'SVC': 'Salvadoran Colon',
    'SYP': 'Syrian Pound',
    'SZL': 'Lilangeni',
    'THB': 'Baht',
    'TJS': 'Tajikistan Ruble',
    'TMT': 'Manat',
    'TND': 'Tunisian Dinar',
    'TOP': 'Pa√ïanga',
    'TRY': 'Lira',
    'TTD': 'Trinidad and Tobago Dollar',
    'TWD': 'Dollar',
    'TZS': 'Shilling',
    'UAH': 'Hryvnia',
    'UGX': 'Shilling',
    'USD': 'USD',
    'UYU': 'Peso',
    'UZS': 'Som',
    'VEF': 'Bolivar',
    'VND': 'Dong',
    'VUV': 'Vatu',
    'XAF': 'CFA Franc BEAC',
    'XCD': 'East Caribbean Dollar',
    'XOF': 'CFA Franc BCEAO',
    'XPF': 'CFP Franc',
    'YER': 'Rial',
    'ZAR': 'Rand',
    'ZMK': 'Kwacha',
    'ZWD': 'Zimbabwe Dollar',
  };

  static const countryCodes = <String, String>{
    'AD': 'EUR',
    'AE': 'AED',
    'AF': 'AFN',
    'AG': 'XCD',
    'AI': 'XCD',
    'AL': 'ALL',
    'AM': 'AMD',
    'AN': 'ANG',
    'AO': 'AOA',
    'AQ': 'AQD',
    'AR': 'ARS',
    'AS': 'EUR',
    'AT': 'EUR',
    'AU': 'AUD',
    'AW': 'ANG',
    'AX': 'EUR',
    'AZ': 'AZN',
    'BA': 'BAM',
    'BB': 'BBD',
    'BD': 'BDT',
    'BE': 'EUR',
    'BF': 'XOF',
    'BG': 'BGN',
    'BH': 'BHD',
    'BI': 'BIF',
    'BJ': 'XOF',
    'BL': 'EUR',
    'BM': 'BMD',
    'BN': 'BND',
    'BO': 'BOB',
    'BR': 'BRL',
    'BS': 'BSD',
    'BT': 'INR',
    'BV': 'NOK',
    'BW': 'BWP',
    'BY': 'BYR',
    'BZ': 'BZD',
    'CA': 'CAD',
    'CC': 'AUD',
    'CD': 'CDF',
    'CF': 'XAF',
    'CG': 'XAF',
    'CH': 'CHF',
    'CI': 'XOF',
    'CK': 'NZD',
    'CL': 'CLP',
    'CM': 'XAF',
    'CN': 'CNY',
    'CO': 'COP',
    'CR': 'CRC',
    'CU': 'CUP',
    'CV': 'CVE',
    'CX': 'AUD',
    'CY': 'CYP',
    'CZ': 'CZK',
    'DE': 'EUR',
    'DJ': 'DJF',
    'DK': 'DKK',
    'DM': 'XCD',
    'DO': 'DOP',
    'DZ': 'DZD',
    'EC': 'ECS',
    'EE': 'EEK',
    'EG': 'EGP',
    'EH': 'MAD',
    'ER': 'ETB',
    'ES': 'EUR',
    'ET': 'ETB',
    'FI': 'EUR',
    'FJ': 'FJD',
    'FK': 'FKP',
    'FM': 'USD',
    'FO': 'DKK',
    'FR': 'EUR',
    'GA': 'XAF',
    'GB': 'GBP',
    'GD': 'XCD',
    'GE': 'GEL',
    'GF': 'EUR',
    'GG': 'GGP',
    'GH': 'GHS',
    'GI': 'GIP',
    'GL': 'DKK',
    'GM': 'GMD',
    'GN': 'GNF',
    'GP': 'EUR',
    'GQ': 'XAF',
    'GR': 'EUR',
    'GS': 'GBP',
    'GT': 'GTQ',
    'GU': 'USD',
    'GW': 'XOF',
    'GY': 'GYD',
    'HK': 'HKD',
    'HM': 'AUD',
    'HN': 'HNL',
    'HR': 'HRK',
    'HT': 'HTG',
    'HU': 'HUF',
    'ID': 'IDR',
    'IE': 'EUR',
    'IL': 'ILS',
    'IM': 'GBP',
    'IN': 'INR',
    'IO': 'USD',
    'IQ': 'IQD',
    'IR': 'IRR',
    'IS': 'ISK',
    'IT': 'EUR',
    'JE': 'GBP',
    'JM': 'JMD',
    'JO': 'JOD',
    'JP': 'JPY',
    'KE': 'KES',
    'KG': 'KGS',
    'KH': 'KHR',
    'KI': 'AUD',
    'KM': 'KMF',
    'KN': 'XCD',
    'KP': 'KPW',
    'KR': 'KRW',
    'KW': 'KWD',
    'KY': 'KYD',
    'KZ': 'KZT',
    'LA': 'LAK',
    'LB': 'LBP',
    'LC': 'XCD',
    'LI': 'CHF',
    'LK': 'LKR',
    'LR': 'LRD',
    'LS': 'LSL',
    'LT': 'LTL',
    'LU': 'EUR',
    'LV': 'LVL',
    'LY': 'LYD',
    'MA': 'MAD',
    'MC': 'EUR',
    'MD': 'MDL',
    'ME': 'EUR',
    'MF': 'ANG',
    'MG': 'MGA',
    'MH': 'USD',
    'MK': 'MKD',
    'ML': 'XOF',
    'MM': 'MMK',
    'MN': 'MNT',
    'MO': 'MOP',
    'MP': 'USD',
    'MQ': 'EUR',
    'MR': 'MRO',
    'MS': 'XCD',
    'MT': 'MTL',
    'MU': 'MUR',
    'MV': 'MVR',
    'MW': 'MWK',
    'MX': 'MXN',
    'MY': 'MYR',
    'MZ': 'MZN',
    'NA': 'NAD',
    'NC': 'XPF',
    'NE': 'XOF',
    'NF': 'AUD',
    'NG': 'NGN',
    'NI': 'NIO',
    'NL': 'EUR',
    'NO': 'NOK',
    'NP': 'NPR',
    'NR': 'AUD',
    'NU': 'NZD',
    'NZ': 'NZD',
    'OM': 'OMR',
    'PA': 'PAB',
    'PE': 'PEN',
    'PF': 'XPF',
    'PG': 'PGK',
    'PH': 'PHP',
    'PK': 'PKR',
    'PL': 'PLN',
    'PM': 'EUR',
    'PN': 'NZD',
    'PR': 'USD',
    'PS': 'JOD',
    'PT': 'EUR',
    'PW': 'USD',
    'PY': 'PYG',
    'QA': 'QAR',
    'RE': 'EUR',
    'RO': 'RON',
    'RS': 'RSD',
    'RU': 'RUB',
    'RW': 'RWF',
    'SA': 'SAR',
    'SB': 'SBD',
    'SC': 'SCR',
    'SD': 'SDG',
    'SE': 'SEK',
    'SG': 'SGD',
    'SH': 'GBP',
    'SI': 'EUR',
    'SJ': 'NOK',
    'SK': 'SKK',
    'SL': 'SLL',
    'SM': 'EUR',
    'SN': 'XOF',
    'SO': 'SOS',
    'SR': 'SRD',
    'ST': 'STD',
    'SV': 'SVC',
    'SY': 'SYP',
    'SZ': 'SZL',
    'TC': 'USD',
    'TD': 'XAF',
    'TF': 'EUR',
    'TG': 'XOF',
    'TH': 'THB',
    'TJ': 'TJS',
    'TK': 'NZD',
    'TM': 'TMT',
    'TN': 'TND',
    'TO': 'TOP',
    'TP': 'IDR',
    'TR': 'TRY',
    'TT': 'TTD',
    'TV': 'AUD',
    'TW': 'TWD',
    'TZ': 'TZS',
    'UA': 'UAH',
    'UG': 'UGX',
    'UM': 'USD',
    'US': 'USD',
    'USAF': 'USD',
    'UY': 'UYU',
    'UZ': 'UZS',
    'VA': 'EUR',
    'VC': 'XCD',
    'VE': 'VEF',
    'VG': 'USD',
    'VI': 'USD',
    'VN': 'VND',
    'VU': 'VUV',
    'WF': 'XPF',
    'WS': 'EUR',
    'YE': 'YER',
    'YT': 'EUR',
    'ZA': 'ZAR',
    'ZM': 'ZMK',
    'ZW': 'ZWD',
  };
}
