on:
  push:
    branches:
      - develop
name: Deploy
jobs:
  deploy:
    name: Deploy with docker-compose
    runs-on: ubuntu-latest
    steps:
      - uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@206.189.179.107
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          stack_file_name: docker-compose.prod.yml
          deploy_path: /home/bayle/autodo
          args: up --build

