on: push
name: Unit and Widget Tests
jobs:
  test:
    name: Unit and Widget Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter pub get
    - run: echo "${{ secrets.keys_json }}" > keys.json
    - run: flutter pub run pubspec_extract -s keys.json -d lib/generated/keys.dart -c Keys
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/lcov.info
